### PR TITLE
Update goodix.patch

### PR DESCRIPTION
**Pull request by jhenrique09**

### CODE REVIEW

**Review by AmolAmrit — APPROVED** [review]
Loved it! Thanks a lot!

**Comment by Bitti09** [comment]
@AmolAmrit  did you tested it?
I'm getting these errors:
 when applying: https://hastebin.com/odizixoraf.vbs

**Comment by AmolAmrit** [comment]
I haven't checked it. It should be working, try git reset --hard just this, and again apply goodix.patch. you also need a commit in vendor.

**Comment by Bitti09** [comment]
I'm doing a build now, had to apply two more commits to get the build started.
If goodix works  my next los build will include your kernel :+1:

**Pull request merged**
