### PR TITLE
Add option to make jackfixed flashable kernel after ROM compilation

### PR DESCRIPTION
**Pull request by amog787**
- Rather than boot.img, flashable kernel with jack fix is a better solution imo.
- Run ./build.sh from the kernel directory

### CODE REVIEW

**Comment by amog787** [comment]
@amog787 this is fast

**Comment by ASparkOfFire** [comment]
@amog787 A simple patch could have been used instead of copying fixes each time

**Comment by wloot** [comment]
I don't think it's a good idea to put the flash-time script into the kernel source, and it's a stock kernel. :)

**Comment by AmolAmrit** [comment]
@kabirkalsi Is Patch possible in this case?

**Comment by AmolAmrit** [comment]
@wloot thats the reason I did not add it for so long.

**Comment by ASparkOfFire** [comment]
@amolamrit Simply merge commits, using it despite not having problem, works flawlessly in either case.

**Comment by amog787** [comment]
made a patch, works topkek, will check if it conflicts when rom is being compiled, if all fine, will make another PR

**Pull request closed without merging**
