### PR TITLE
Pull Request #2

### PR DESCRIPTION
**Pull request by amanrajOO7**

### CODE REVIEW

**Comment by AmolAmrit** [comment]
@amanrajOO7 No please

**Comment by amanrajOO7** [comment]
It was by mistake sir, I was just checking the commits & comparing it with my Trees.

**Comment by AmolAmrit** [comment]
@amanrajOO7 Nevermind sir

**Comment by amanrajOO7** [comment]
You're sir, sir. I'm not

**Comment by AmolAmrit** [comment]
@amanrajOO7 Just doing this, doesn't make me sir at all. 
In real life you are far better than I am.

**Comment by amanrajOO7** [comment]
In real life, nobody is better & nobody is worse. Everybody is better in something & worse in something else.

**Pull request closed without merging**
